### ISSUE TITLE
Blocking whole feed

### ISSUE THREAD

**Issue by unoexperto** [lucboruta/linkedin-feed-blocker#7]
@lucboruta Luc, thank you for your plugin. I'm not sure if I misunderstood the description but isn't it supposed to block only promoted posts ? Unfortunately in my case it's blocking all feeds (personal and companies' feeds).

I'm using Brave browser (Version 1.22.70 Chromium: 89.0.4389.105 (Official Build) (64-bit))

**Comment by lucboruta** [comment]
Hi, thank you for your interest in the extension. It was indeed designed to block **all** posts in the feed, as illustrated by the screenshot on the Chrome web store.

The extension is very simple by design, and I have no plans to add code for some types of posts to be blocked and not others. That being said, I'd be happy to review a pull request if you want to give it a shot.

I'll leave this issue open to rework the description next time I submit an update to the Chrome web store.

**Comment by njelich** [comment]
If you want to filter the feed rather than block it, check out [this extension.](https://github.com/njelich/linkoff)

**Comment by lucboruta** [comment]
This extension is no longer maintained. Please consider using @njelich's [LinkOff](https://github.com/njelich/linkoff) instead.
